[window]
padding.x = 10
padding.y = 10
decorations = "Full"
dynamic_padding = true

[font]
normal.family = "JetBrains Mono"
size = 12.0

general.import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
