[window]
padding.x = 10
padding.y = 10
decorations = "Full"
dynamic_padding = true

[font]
normal.family = "JetBrains Mono"
size = 12.0

[colors.primary]
background = "0x1e1e2e"
foreground = "0xc0caf5"

[env]
TERM = "xterm-256color"